### ISSUE TITLE
Sometimes uninitialized logger stacktrace

### ISSUE THREAD

**Issue by adrianrobotka** [submariner-io/subctl#861]
**What happened**:

Rarely, `subctl` output gets polluted with a stacktrace caused by `log.SetLogger(...) was never called`.
I am not sure when exactly (maybe just on `join` or deploy-broker). I assume it happens on a race.
It does not break the execution, but extra error logs are not expected in the run.

**What you expected to happen**:

No error logs about `log.SetLogger(...) was never called`.

**How to reproduce it (as minimally and precisely as possible)**:

Just a guess: Run `subctl` 1-3 times (e.g. `join`).

**Anything else we need to know?**:

**Environment**:

I used the devel branch (a5e27578).

An example log sample:

```text
[controller-runtime] log.SetLogger(...) was never called, logs will not be displayed:
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/lib/golang/src/runtime/debug/stack.go:24 +0x65
sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	/home/adr/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/log/log.go:59 +0xbd
sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Enabled(0xc0003b3100, 0xc00198e000?)
	/home/adr/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/log/deleg.go:111 +0x3d
github.com/go-logr/logr.Logger.Enabled(...)
	/home/adr/go/pkg/mod/github.com/go-logr/logr@v1.2.4/logr.go:261
github.com/go-logr/logr.Logger.Info({{0x37bb378?, 0xc0003b3100?}, 0xc0007f3628?}, {0xc001bc2000, 0x58a0}, {0x0, 0x0, 0x0})
	/home/adr/go/pkg/mod/github.com/go-logr/logr@v1.2.4/logr.go:274 +0x78
github.com/submariner-io/admiral/pkg/log.Logger.Infof({{{0x37bb378?, 0xc0003b3100?}, 0x588d?}}, {0x329fe6e?, 0x3277b42?}, {0xc0007f3628?, 0x0?, 0x37b78d0?})
	/home/adr/go/pkg/mod/github.com/submariner-io/admiral@v0.16.0-m2/pkg/log/logger.go:42 +0x74
github.com/submariner-io/admiral/pkg/util.maybeCreateOrUpdate.func1()
	/home/adr/go/pkg/mod/github.com/submariner-io/admiral@v0.16.0-m2/pkg/util/create_or_update.go:148 +0xa85
k8s.io/client-go/util/retry.OnError.func1()
	/home/adr/go/pkg/mod/k8s.io/client-go@v0.27.3/util/retry/util.go:51 +0x33
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0xc0007f36e0?)
	/home/adr/go/pkg/mod/k8s.io/apimachinery@v0.27.3/pkg/util/wait/wait.go:145 +0x4d
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff({0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0}, 0xc0019ec000?)
	/home/adr/go/pkg/mod/k8s.io/apimachinery@v0.27.3/pkg/util/wait/backoff.go:461 +0x5f
k8s.io/client-go/util/retry.OnError({0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0}, 0x0?, 0xc8?)
	/home/adr/go/pkg/mod/k8s.io/client-go@v0.27.3/util/retry/util.go:50 +0xa8
k8s.io/client-go/util/retry.RetryOnConflict(...)
	/home/adr/go/pkg/mod/k8s.io/client-go@v0.27.3/util/retry/util.go:104
github.com/submariner-io/admiral/pkg/util.maybeCreateOrUpdate({0x37b78d0?, 0xc000058168?}, {0x37b8e40?, 0xc000875da0?}, {0x37a3400?, 0xc0019ec000?}, 0x33f3230?, 0x2?)
	/home/adr/go/pkg/mod/github.com/submariner-io/admiral@v0.16.0-m2/pkg/util/create_or_update.go:87 +0x1c8
github.com/submariner-io/admiral/pkg/util.Update(...)
	/home/adr/go/pkg/mod/github.com/submariner-io/admiral@v0.16.0-m2/pkg/util/create_or_update.go:71
github.com/submariner-io/subctl/pkg/uninstall.unlabelGatewayNodes({0x37a8ec0, 0xc00069a2d0}, {0xc00005af90, 0x2c}, {0x37ba910, 0xc00037ed90})
	/home/adr/codes/subctl/pkg/uninstall/all.go:121 +0x4cb
github.com/submariner-io/subctl/pkg/uninstall.All({0x37a8ec0, 0xc00069a2d0}, {0xc00005af90, 0x2c}, {0x329ba47, 0x13}, {0x37ba910, 0xc00037ed90})
	/home/adr/codes/subctl/pkg/uninstall/all.go:96 +0x431
github.com/submariner-io/subctl/cmd/subctl.uninstallInContext(0xc00011b880?, {0x329ba47?, 0x13?}, {0x37ba910?, 0xc00037ed90?})
	/home/adr/codes/subctl/cmd/subctl/uninstall.go:72 +0x1e6
github.com/submariner-io/subctl/internal/restconfig.(*Producer).RunOnSelectedContext(0xc00033cee0, 0x33f3138, {0x37ba910, 0xc00037ed90})
	/home/adr/codes/subctl/internal/restconfig/restconfig.go:230 +0x21d
github.com/submariner-io/subctl/cmd/subctl.glob..func34(0x4dbb520?, {0x3278d61?, 0x0?, 0x0?})
	/home/adr/codes/subctl/cmd/subctl/uninstall.go:46 +0x38
github.com/spf13/cobra.(*Command).execute(0x4dbb520, {0x4f3dd40, 0x0, 0x0})
	/home/adr/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x4db92a0)
	/home/adr/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/adr/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/submariner-io/subctl/cmd/subctl.Execute()
	/home/adr/codes/subctl/cmd/subctl/root.go:68 +0x25
main.main()
	/home/adr/codes/subctl/cmd/main.go:24 +0x17
```

**Comment by tpantelis** [comment]
This is fixed by https://github.com/submariner-io/subctl/pull/830 which will be in 0.16 release.
